### ISSUE TITLE
Error when deleting edges.

### ISSUE THREAD

**Issue by jeffbloomberg** [the-data-lab/GraphOne#12]
Hi I am getting various errors when deleting edges from the graph. Setting the -DEL flag results in a segfault, and having no flag resuults in an assert failure.

Please see this gist of the code I am running.  https://gist.github.com/jeffbloomberg/18fe836d9f2e91031e2528c4ebdf166c

I compile using this command: (running g++ 9.2.)
`g++ --std=c++17 reproduce.cpp -DOVER_COMMIT -DDEL -DEL -DTBB -DPLAIN_GRAPH -DB64 -Isrc -Igview -Iinclude -Ionedata -Ianalytics -o3 -g -Wall -fopenmp -pthread build/src/libsrc64.a build/onedata/libonedata64.a -ltbb -o reproduce.out`

Without the -DEL flag I simply get  `compare_graphone: /home/jeff/CLionProjects/graphOne/src/edge_sharding.h:494: void edge_shard_t<T>::estimate_classify(vid_t*, vid_t*, vid_t, vid_t) [with T = dst_weight_t<__univeral_type>; vid_t = long unsigned int]: Assertion `range < RANGE_COUNT' failed.`

**Comment by pradeep-k** [comment]
Around line 91, you forgot to initialize. Write this code `partition_start = 0;`

`-DDEL` is correct not `-DEL`.  Rest of the things looks good. Please re-run your

**Comment by jeffbloomberg** [comment]
Thank you pradeep-k. This has fixed my issue.
