### ISSUE TITLE
Historical view API Bug

### ISSUE THREAD

**Issue by CuiMingyu** [the-data-lab/GraphOne#15]
Hi, would it be possible for you to give more APIs in Readme file? Thank you so much!

**Comment by CuiMingyu** [comment]
Also, I have a question that whether all the APIs are shown in paper or there are still a few more APIs? Thank you for your time!

**Comment by pradeep-k** [comment]
All the APIs listed in paper are present in the code. Kindly have a look inside gview folder.
Each file generally corresponds to one class of APIs, called GraphView. view_interface.h contains the base class.

static_view, sstream_view, wsstream_view, stream_view, and historical_view (limited support) are there. 

If you need any specific information about any of those, feel free to post here.

**Comment by pradeep-k** [comment]
I will try to update the README file as soon as possible. Thanks for the suggestion.

**Comment by CuiMingyu** [comment]
Thank you for your reply! I'll check it soon.

**Comment by CuiMingyu** [comment]
Hi, I have another question that would it be possible to get graph in every snapshot. I mean in your paper, each batch of edges is recorded in snapshots. Can I get the graph in snapshot_1 and get another graph in snapshot_2?  How to operate it?  I read your code but I can't figure it out.  For example, there is a graph containing 8 edges and 4 edges a snapshot. Thus, as for this graph there are two snapshots. Can I get the graph which contains 4 edges in the first snapshot and get the later graph containing 8 edges in the second snapshot? If possible, how to finish this process?  After reading your code, I only found snaph->get_snapid() and snaph->get_snapmaker(). I don't know how to achieve it. Do you have any advice on it? Thank you.

**Comment by pradeep-k** [comment]
We do have historical views that will help you in getting the older snapshots.   I haven't used this view for long. Let me know, if you have any issues in using it. I can fix  if you find any issues. 

It gives you access to any historical window. It accepts you to pass two offsets. Passing 0 and 4 will give you access to S_1, and passing 0 and 8 will give you access to S_2.

If you can't figure out the details, let me know, i will consider updating the documentation.

**Comment by CuiMingyu** [comment]
Thank you!!!!! I will check it. I just always read static_view.h and plain_test.h and forgot the history view. 
Thank you! I will try it!

**Comment by CuiMingyu** [comment]
Hello, I meet a problem when I am trying to create history view of a graph. I just use the code in job 6 prior_snap_test and it gives me an error below.
`graphone32: /home/parallels/Public/GraphOne-master/src/sgraph.h:702: void pgraph_t<T>::create_degree(degree_t*, degree_t*, index_t, index_t) [with T = dst_id_t; degree_t = int; index_t = long unsigned int]: Assertion `size == sz_read' failed.
`
I try to print size and sz_read. They are 64 and 18446744073709551615 respectively. I just use a graph with 9 vertex.

Could you help me fix it?  Many thanks.

**Comment by pradeep-k** [comment]
I am sure that it may have bug as I have not tested this case for long. 

Can you give me your command line arguments?

**Comment by CuiMingyu** [comment]
Sure. But I changed some code. I put `prior_snap_t<T>* snaph1 = create_prior_static_view(pgraph1, 0, 8);` into function run_bfs in job 0. So the command line likes the old one.
`./graphone32  -i test_data/ -j 0 -v 9`

**Comment by pradeep-k** [comment]
Can you confirm if the test also fails when you use -o flag as well. Before that you need to create output directory `out`.

`./graphone32 -i test_data/ -j 0 -v 9 -o ./out/`

**Comment by CuiMingyu** [comment]
It works. Thanks a lot.

**Comment by pradeep-k** [comment]
Thank you for confirming. 

Don't hesitate to update this thread, if you find any bug.

**Comment by CuiMingyu** [comment]
Sure, I will. But it crashed. I output the size and sz_read. Then Segmentation fault.

**Comment by CuiMingyu** [comment]
> Sure, I will. But it crashed. I output the size and sz_read. Then Segmentation fault.

`
size: 40
sz_read: 40
Segmentation fault (core dumped)
`

**Comment by pradeep-k** [comment]
Testcase 6 is the not the correct testcase. 

I will provide you a new testcase soon.

**Comment by CuiMingyu** [comment]
Many thanks!!!!!

**Comment by CuiMingyu** [comment]
Hi, one more question. When I use deezer dataset and I met a problem.
`/graphone32 -i deezer/ -j 0 -v 54573 -d 1
input dir = deezer/
Global vcount = 54573
Threads Count = 1
huge page alloc failed while reading input dir
Reading 1 file time = 0.00274801
total size = 5769726
  Read/alloc time = 0.0028522
Segmentation fault (core dumped)
`
I am wondering that whether the dataset is too large. Dataset is Graph Embedding with Self Clustering: Deezer, February 13 2018. And I change HR.csv into .txt.

Dataset website:
https://snap.stanford.edu/data/gemsec-Deezer.html

**Comment by CuiMingyu** [comment]
But I can use https://snap.stanford.edu/data/ego-Facebook.html to test.

**Comment by pradeep-k** [comment]
I recieved some message as part of this bug, mentioning deezer dataset. Unfortunately, I can't see the update here.  Did you delete your update?

**Comment by CuiMingyu** [comment]
Sorry, I fixed the bug. It's about my mistakes. Thank you.

**Comment by pradeep-k** [comment]
The historical snapshot view is now working, with an added example (-j 6).
Here is the output.  Do let me know, if you need any more information here.
```
pkumar@mira:~/GraphOne/build$ ./graphone32 -i ~/data/kron-21/bin/ -v 2097152 -j 6 -s 1 -d0 -o ./out/
input dir = /home/pkumar/data/kron-21/bin/
Global vcount = 2097152
output dir = ./out/
Threads Count = 19
enterting w_func
 Batching Time = 1.75779 vertex count = 2097152
Batch Update Time = 1.75794 edges = 33554432
Durable Graph Time = 1.76259
Make Graph Time = 1.76996
BFS Time = 0.045006
 Level = 0 count = 1
 Level = 1 count = 1
 Level = 2 count = 24596
 Level = 3 count = 795485
 Level = 4 count = 223717
 Level = 5 count = 2245
 Level = 6 count = 17
```

**Comment by CuiMingyu** [comment]
Many thanks. I will try it soon. Thank you!

**Comment by pradeep-k** [comment]
I am closing this issue. If you have any issues, raise another bug. 
Thanks.
