### ISSUE TITLE
[question] Garbage collector

### ISSUE THREAD

**Issue by whatsthecraic** [the-data-lab/GraphOne#19]
Hi Pradeep,
was it implemented some form of garbage collector in the library, to remove unused versions & the tombstones from the adjacency lists?

**Comment by pradeep-k** [comment]
Yes. Both should be there in feature branch.  I think I informed you about that sometime back in some of the issues, and you s

An improved version is also with us on a private repository. We will be merging our private repo to the main branch of this code base in a few weeks. 

If you have not started using feature branch, I will suggest you to wait for a few weeks for the merge. We are working on it to merge.

**Comment by whatsthecraic** [comment]
just to confirm, the current `master' branch does not contain a garbage collector. Correct?

Thanks a lot!

**Comment by pradeep-k** [comment]
That’s right.

**Comment by whatsthecraic** [comment]
oky, thanks!

**Comment by pradeep-k** [comment]
I updated the above description.
