### ISSUE TITLE
Error running archive test ( -j 2)

### ISSUE THREAD

**Issue by pradeepfn** [the-data-lab/GraphOne#20]
I tried running archive testcase from master branch code.

used the command: ./graphone32 -i ../data/ -j 2 -v 2097152

I generated kron21_16 as per the instructions in the project readme. Output filename turns out to be scale-21-rank-0-of-1-par-rowcol-0-0.dat ( in case it helps).

error output:

input dir = ../data/
Global vcount = 2097152
Threads Count = 111
Reading 1 file time = 0.271577
End marker = 62577182
batch_size = 1
graphone32: /home/cyclone/graph-one/src/edge_sharding.h:485: void edge_shard_t<T>::estimate_classify(vid_t*, vid_t*, vid_t, vid_t) [with T = dst_id_t; vid_t = unsigned int]: Assertion `range < RANGE_COUNT' failed.
Aborted (core dumped)

**Comment by pradeep-k** [comment]
the generated dat files implies that you have generated a binary file. Try passing -s1 option and let me know if it works.

**Comment by pradeep-k** [comment]
This command line option worked:
`./graphone32 -i ~/data/kron-21/bin/ -j 2 -v 2097152 -r 16 -s 1`
