### ISSUE TITLE
I can't find ltbb

### ISSUE THREAD

**Issue by gaodechao** [the-data-lab/GraphOne#22]
gaodc@hadoop2:~/Desktop/code/GraphOne/build$ cmake ../
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gaodc/Desktop/code/GraphOne/build
gaodc@hadoop2:~/Desktop/code/GraphOne/build$ ls
CMakeCache.txt  CMakeFiles  cmake_install.cmake  Makefile  onedata  src  test
gaodc@hadoop2:~/Desktop/code/GraphOne/build$ make
Scanning dependencies of target src32
[  2%] Building CXX object src/CMakeFiles/src32.dir/cf_info.cpp.o
[  4%] Building CXX object src/CMakeFiles/src32.dir/enumkv.cpp.o
[  7%] Building CXX object src/CMakeFiles/src32.dir/graph.cpp.o
[  9%] Building CXX object src/CMakeFiles/src32.dir/prop_encoder.cpp.o
[ 11%] Building CXX object src/CMakeFiles/src32.dir/sgraph.cpp.o
[ 14%] Building CXX object src/CMakeFiles/src32.dir/stringkv.cpp.o
[ 16%] Building CXX object src/CMakeFiles/src32.dir/typekv.cpp.o
[ 19%] Linking CXX static library libsrc32.a
[ 19%] Built target src32
Scanning dependencies of target test32
[ 21%] Building CXX object test/CMakeFiles/test32.dir/csv_to_edge.cpp.o
[ 23%] Building CXX object test/CMakeFiles/test32.dir/lanl15_test.cpp.o
[ 26%] Building CXX object test/CMakeFiles/test32.dir/multi_graph.cpp.o
[ 28%] Building CXX object test/CMakeFiles/test32.dir/multigraph_test.cpp.o
[ 30%] Building CXX object test/CMakeFiles/test32.dir/nt_to_edge.cpp.o
[ 33%] Building CXX object test/CMakeFiles/test32.dir/plaingraph_test.cpp.o
/home/gaodc/Desktop/code/GraphOne/test/plaingraph_test.cpp: In instantiation of ‘void multi_stream_bfs(const string&, const string&, typename callback<T>::sfunc, int) [with T = dst_id_t; std::__cxx11::string = std::__cxx11::basic_string<char>; typename callback<T>::sfunc = void (*)(gview_t<dst_id_t>*)]’:
/home/gaodc/Desktop/code/GraphOne/test/plaingraph_test.cpp:1359:71:   required from here
/home/gaodc/Desktop/code/GraphOne/test/plaingraph_test.cpp:1244:60: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
                             STALE_MASK|V_CENTRIC|C_THREAD, (void*)(i+1));
                                                            ^~~~~~~~~~~~
In file included from /home/gaodc/Desktop/code/GraphOne/test/plaingraph_test.cpp:3:0:
/home/gaodc/Desktop/code/GraphOne/test/plain_to_edge.h: In instantiation of ‘void plaingraph_manager_t<T>::split_files(const string&, const string&) [with T = dst_weight_t<__univeral_type>; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/home/gaodc/Desktop/code/GraphOne/test/plaingraph_test.cpp:758:5:   required from ‘void split_files(const string&, const string&) [with T = dst_weight_t<__univeral_type>; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/gaodc/Desktop/code/GraphOne/test/plaingraph_test.cpp:1349:49:   required from here
/home/gaodc/Desktop/code/GraphOne/test/plain_to_edge.h:301:16: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘index_t {aka long unsigned int}’ [-Wformat=]
         sprintf(tmp, "%d.dat", residue);
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
[ 35%] Building CXX object test/CMakeFiles/test32.dir/util.cpp.o
[ 38%] Linking CXX static library libtest32.a
[ 38%] Built target test32
Scanning dependencies of target onedata32
[ 40%] Building CXX object onedata/CMakeFiles/onedata32.dir/onestr.cpp.o
[ 42%] Linking CXX static library libonedata32.a
[ 42%] Built target onedata32
Scanning dependencies of target graphone32
[ 45%] Building CXX object CMakeFiles/graphone32.dir/main.cpp.o
[ 47%] Linking CXX executable graphone32
/usr/bin/ld: 找不到 -ltbb
collect2: error: ld returned 1 exit status
CMakeFiles/graphone32.dir/build.make:106: recipe for target 'graphone32' failed
make[2]: *** [graphone32] Error 1
CMakeFiles/Makefile2:166: recipe for target 'CMakeFiles/graphone32.dir/all' failed
make[1]: *** [CMakeFiles/graphone32.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pradeep-k** [comment]
You need to install intel tbb library.  Here is a link for instruction on ubuntu:
`https://askubuntu.com/questions/1170054/install-newest-tbb-thread-building-blocks-on-ubuntu-18-04'

If you can't install, you can disable tbb through CMakeLists.txt by removing -ltbb and -DTBB from it.

**Comment by gaodechao** [comment]
Thanks, this problem is solved
