### ISSUE TITLE
How do I run WCC

### ISSUE THREAD

**Issue by MagamanX** [the-data-lab/GraphOne#23]
Hello, I tried various ways to run -j 33's WCC algorithm but failed every time.  
used the command: ./graphone32 -i /ContrastSystem/weibo/ -j 33 -v 1787443 -d 1 -r 10 -e 423071214 -o ./db/

error output:
input dir = /ContrastSystem/weibo/
Global vcount = 1787443
residue (multi-purpose) value) = 10
output dir = ./db/
Threads Count = 47
created sstream thread
enterting w_func
Segmentation fault (core dumped)

I can run the -j 0 algorithm successfully, but a segment error occurs in the -j 33 algorithm. Is there a mistake in my command input?

Thanks.

**Comment by pradeep-k** [comment]
Can you paste here `ls` output when your current directory is `/ContrastSystem/weibo/` and a few lines of your graph file content.

I think your input path (-i) seems incorrect. Do you wanted it to be `-i ./ContrastSystem/weibo/` 

If everything looks fine, can you run it in gdb, and paste the stack trace of the corruption.

1.   make sure to compile graphone in Debug mode.
2. run it in gdb using `gdb --args ./graphone32 -i /ContrastSystem/weibo/ -j 33 -v 1787443 -d 1 -r 10 -e 423071214 -o ./db/` . Once it fails, type `bt` and paste the output here.

**Comment by MagamanX** [comment]
My input path is indeed that. 

/ContrastSystem/weibo/ `ls` output:
![QQ图片20220502075305](https://user-images.githubusercontent.com/29134920/166169986-54861ffc-1083-4705-98e0-b508d9b6d188.png)

And the number of lines of graph file content:
![QQ图片20220502080420](https://user-images.githubusercontent.com/29134920/166170179-9a946767-41c2-4486-8442-b6d6f13ab14a.png)

Finally, the debug output:
![QQ图片20220502074552](https://user-images.githubusercontent.com/29134920/166170110-986e056a-fee6-42cb-89ee-63e884e113ac.png)

**Comment by pradeep-k** [comment]
Thank you very much for the information.
I have some idea now on where the bug is. Give me a day or two, I will try to reproduce the error and fix it.

On a side note, do you want to try new version of GraphOne. It is a private repo, but I can enable access for you.  The new repo will have fixes for this bug. I will anyway merge the new repo with GraphOne repo in a couple of weeks, so it will be seamless for you.  Do you want me to give you access?

**Comment by MagamanX** [comment]
Thanks! please let me try the new version of GraphOne. I am looking forward to it.

**Comment by pradeep-k** [comment]
New repository works for this testcase ater I ran it.. I am working on uploading the new version here.

**Comment by pradeep-k** [comment]
I added you to the repository. 
For the testcase, that you are trying, you should use following commands:

```
pkumar@mira:~/dist-graph/build$ ./graphone32 -c 1 -j 0 -i ~/data/kron-21/text/ -v 2097152
 Input dir = /home/pkumar/data/kron-21/text/
 Output dir = 
 Batch size =65536
 Threads Count = 10: 10
 Vertex Count = 2097152
 residue (multi-purpose) value) = 0
created sstream thread
 Logging Time from Files = 8.34034
Batch Update Time (File) = 8.34051 Edge_count = 33554432 THD_COUNT = 10
stream wcc done.  Not Printing output
```

**Comment by MagamanX** [comment]
Thanks! I'll give it a try right now

**Comment by pradeep-k** [comment]
Just to be sure. The new repository has not been merged yet. Hence, I have provided you a permission to the new repository. You should have got an email for the same.
