### ISSUE TITLE
Can't make file.

### ISSUE THREAD

**Issue by CuiMingyu** [the-data-lab/GraphOne#6]
Sorry about that. When I am following the first step to build, it shows below error.

`[  2%] Building CXX object src/CMakeFiles/src64.dir/cf_info.cpp.o
clang: error: unsupported option '-fopenmp'
make[2]: *** [src/CMakeFiles/src64.dir/cf_info.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/src64.dir/all] Error 2
make: *** [all] Error 2`

I have tried many methods to figure it out, but none of methods can work.

**Comment by pradeep-k** [comment]
-fopenmp flag means the presence of openMP support in your compiler. What is your compiler, does it have openMP support, if yes, what flag does your compiler provides if not -fopenmp?

**Comment by pradeep-k** [comment]
https://stackoverflow.com/questions/33357029/using-openmp-with-clang reveals that clang may have issues using openMP. I have not used clang, so unaware about what is the current status of clang. Hope you will be able to figure out openMP support in clang compiler.

**Comment by CuiMingyu** [comment]
> https://stackoverflow.com/questions/33357029/using-openmp-with-clang reveals that clang may have issues using openMP. I have not used clang, so unaware about what is the current status of clang. Hope you will be able to figure out openMP support in clang compiler.

Thank you. I fixed the problem.

**Comment by pradeep-k** [comment]
Thank you very much for this information. Feel free to reach out, if you face any other issues.
